# Generated by Django 3.2.9 on 2022-02-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='store',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='storetranslation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='storetranslation',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords'),
        ),
    ]
