# Generated by Django 3.2.9 on 2022-02-06 20:39

import accounts.utilities
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osuser',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=accounts.utilities.get_user_avatar_path, verbose_name='Avatar'),
        ),
    ]
